Feature/lab1d
st1lson/ComputerGraphics pull request #3
Opened 2023-03-06 22:12 UTC by decel337

2023-03-06 22:43 UTC, st1lson requested changes

2023-03-06 22:43 UTC, st1lson commented on RenderEngine/RenderEngine/Core/Renderer.cs
> +                        screen[i, j] = Scene.Lighting.FirstOrDefault().GetLight(shape, intersectionPoint);
FirstOrDefault returns nullable<T>, possible null reference exception

2023-03-06 22:43 UTC, st1lson commented on RenderEngine/RenderEngine/Shapes/Disk.cs
> +            if(distanceValue > Radius * Radius)
use conditional expression

2023-03-06 22:43 UTC, st1lson commented on RenderEngine/RenderEngine/Shapes/Sphere.cs
> +                return new Vector3(0, 0, 0);
Vector3 has a static Zero field

2023-03-06 22:43 UTC, st1lson commented on RenderEngine/RenderEngine/Shapes/Triangle.cs
> +        public Vector3 v2 { get; init; }
public properties - CamelCase

2023-03-06 22:43 UTC, st1lson commented on RenderEngine/RenderEngine/Shapes/Triangle.cs
> +            this.v0 = v0;
don't use the 'this' keyword

2023-03-06 22:43 UTC, st1lson commented on RenderEngine/RenderEngine/Shapes/Triangle.cs
> +            if(t <= tolerance)
also can be replaced with conditional expression

2023-03-06 22:43 UTC, st1lson commented on RenderEngine/RenderEngine/Shapes/Triangle.cs
> +            return pvec;
```suggestion
            return Vector3.Cross(edge1, edge2);
```

2023-03-06 23:43 UTC, Akara4ok commented on RenderEngine/RenderEngine/Basic/Point3.cs
> +    public static Point3 operator -(Point3 left, Point3 right)
Invalid operator for point

2023-03-06 23:43 UTC, Akara4ok commented on RenderEngine/RenderEngine/Core/Renderer.cs
> +                        screen[i, j] = Scene.Lighting.FirstOrDefault().GetLight(shape, intersectionPoint);
You have to remember the closest shape and find color for it only in the end

2023-03-06 23:43 UTC, Akara4ok commented on RenderEngine/RenderEngine/Lightings/Light.cs
> +    public class Light : ILighting
Rename to directional light

2023-03-06 23:43 UTC, Akara4ok commented on RenderEngine/RenderEngine.Console/Program.cs
>          //TODO: add some lighting
Delete this comments

2023-03-06 23:43 UTC, Akara4ok commented on RenderEngine/RenderEngine/Shapes/Sphere.cs
> +        public Vector3 GetNormal(Vector3? intersectionPoint)
delete optional value here but use Vector.Value when you pass argument

2023-03-07 11:48 UTC, st1lson approved these changes

2023-03-07 11:48 UTC, Akara4ok approved these changes

2023-03-07 11:50 UTC, merged